Created base implementation for ClientSender. Also updated the makefile.client. Encountered errors 1) undefined reference to 'Thread::~Thread()', and 2) relocation truncated to fit: R_X86_64_PC32 against undefined symbol. Took me 1 hr to realize that I forgot to include the path to thread.cpp inside the SOURCES flag of Makefile.client. Attempted to create destructors for ConnectionHandler, MessageHandler, but realized that I was trying to delete references, which is really stuff, you only delete pointers/ heap memory.